server:
  port: 8080

spring:
  datasource:
    username: user02
    password: Lyc0802!
    url: jdbc:mysql://47.103.29.16:3306/graduation_project
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.application.audit

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
